#!/usr/bin/env bash
#
# Invokes the Sonar Report Generator agent via the NVIDIA API.
# Reads SonarQube JSON artifacts from ./reports/ and writes the
# generated Markdown report to ./reports/sonar-report.md.
#
# Required env:
#   NVDAI_API_KEY      - NVIDIA API key
# Optional env:
#   NVDAI_MODEL        - model id (default: meta/llama-3.1-70b-instruct)
#   NVDAI_MAX_TOKENS   - max tokens (default: 6000)
#
# This is a READ-ONLY agent. It does not modify any source code; it
# only writes reports/sonar-report.md.

set -euo pipefail

if [ -z "${NVDAI_API_KEY:-}" ]; then
  echo "::error::NVDAI_API_KEY is not set; cannot invoke the agent." >&2
  exit 1
fi

REPORTS_DIR="${REPORTS_DIR:-reports}"
mkdir -p "$REPORTS_DIR"

MODEL="${NVDAI_MODEL:-meta/llama-3.1-70b-instruct}"
MAX_TOKENS="${NVDAI_MAX_TOKENS:-6000}"

# Sanity: list the available inputs so the model knows what's there.
echo "📂 SonarQube inputs under $REPORTS_DIR/:" >&2
ls -la "$REPORTS_DIR" >&2 || true

SYSTEM_PROMPT='You are the "Sonar Report Generator Agent", an expert DevSecOps Security Reporting Agent.

Your responsibility is to generate a professional Markdown report from SonarCloud/SonarQube analysis results.

ABSOLUTE RULES (non-negotiable):
1. You DO NOT modify source code.
2. You DO NOT fix vulnerabilities.
3. You DO NOT make assumptions.
4. You DO NOT invent data.
5. You ONLY convert SonarCloud analysis into a Markdown report.
6. You write exactly ONE file: reports/sonar-report.md
7. If any input is missing, mark that section "Not Available" and continue.
8. Numbers MUST exactly match SonarCloud. Never estimate. Never calculate manually.
9. The report must be deterministic: sort all aggregates before emission.

INPUTS (already on disk under reports/):
- reports/sonar-report.json   (issues[] array — the most important input)
- reports/quality-gate.json   (projectStatus.status and projectStatus.conditions[])
- reports/measures.json       (component.measures[])
- reports/hotspots.json       (hotspots[])
- reports/project.json        (component.{key,name,organization,visibility,analysisDate})
- reports/report-metadata.json ({project, repository, branch, commit, generated})

OUTPUT FORMAT:
Follow the EXACT report structure defined in the agent specification. Sections must appear in this order and only this order:

  # SonarQube Security Analysis Report
  ## Executive Summary (Quality Gate + Overall Risk table)
  ## Dashboard Summary (Bugs/Vulnerabilities/Code Smells/Security Hotspots/Coverage/Duplicated Code/Reliability Rating/Security Rating/Maintainability Rating)
  ## Severity Summary (Blocker/Critical/Major/Minor/Info)
  ## Detailed Findings (group by severity: BLOCKER, CRITICAL, MAJOR, MINOR, INFO; sort within each by file then line ascending)
  ## Security Hotspots
  ## Bugs
  ## Vulnerabilities
  ## Code Smells
  ## Files With Highest Issues (sort descending by count, then ascending by file path)
  ## Rule Frequency (sort descending by count, then ascending by rule)
  ## OWASP Mapping (if any issue tags match ^owasp-)
  ## AI Summary (max 10 bullets; never recommend fixes)
  ## Report Footer (Generated By, Generated On — UTC ISO 8601 timestamp)

Use proper Markdown tables. Use emojis only for severity indicators (🔴 CRITICAL, 🟠 MAJOR, 🟡 MINOR, 🔵 INFO, ⚪ BLOCKER).'

USER_PROMPT='Read every JSON file under ./reports/ and produce the SonarQube Security Analysis Report in EXACTLY the format specified. Output ONLY the Markdown content of the report — no preamble, no explanation, no code fences around the whole report. The first line MUST be the report title "# SonarQube Security Analysis Report".'

# Write the two prompts to files so python can read them with no shell escaping.
printf '%s' "$SYSTEM_PROMPT" > system-prompt.txt
printf '%s' "$USER_PROMPT"   > user-prompt.txt

# Build payload.json from the prompt files.
PY="${PYTHON:-python3}"
if ! command -v "$PY" >/dev/null 2>&1; then
  PY="python"
fi
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "::error::Neither python3 nor python is available; cannot build payload." >&2
  exit 1
fi
"$PY" - <<'PYEOF'
import json, os
with open("system-prompt.txt", "r", encoding="utf-8") as f:
    system_content = f.read()
with open("user-prompt.txt", "r", encoding="utf-8") as f:
    user_content = f.read()
payload = {
    "model": os.environ.get("NVDAI_MODEL", "meta/llama-3.1-70b-instruct"),
    "max_tokens": int(os.environ.get("NVDAI_MAX_TOKENS", "6000")),
    "messages": [
        {"role": "system", "content": system_content},
        {"role": "user",   "content": user_content},
    ],
}
with open("payload.json", "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False)
print("payload.json written:", os.path.getsize("payload.json"), "bytes")
PYEOF

echo "────────────────────────────────────────────"
echo "🤖 Agent - Sonar Report Generator"
echo "────────────────────────────────────────────"

RESPONSE=$(curl -s https://integrate.api.nvidia.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $NVDAI_API_KEY" \
  -d @payload.json)

# Persist the report as an artifact.
echo "$RESPONSE" | jq -r '.choices[0].message.content // "Agent response unavailable"' 2>/dev/null \
  > "$REPORTS_DIR/sonar-report.md" \
  || echo "Agent response processing failed" > "$REPORTS_DIR/sonar-report.md"

echo "📝 Report written to $REPORTS_DIR/sonar-report.md" >&2
wc -l "$REPORTS_DIR/sonar-report.md" >&2 || true

echo "────────────────────────────────────────────"

# Clean up the payload and prompt files.
rm -f payload.json system-prompt.txt user-prompt.txt
